### ISSUE TITLE
Intermittent Response Error when trying to play videos

### ISSUE THREAD

**Issue by miller-design** [marco-land/sanity-plugin-vimeo-field#5]
Hi there,

Quick question, I seem to be getting some intermittent errors when trying to play videos on the site. The data all gets fetched from the plugin correctly but every so often the site will display a bunch of net::ERR_HTTP2_PROTOCOL_ERROR messages which seems to be an issue with the response headers. 

I was just wondering if you have had any similar issues with this? 

![Screenshot 2024-07-09 at 11 19 24](https://github.com/marco-land/sanity-plugin-vimeo-field/assets/72648825/e1633c03-daed-42ca-ac14-b904c560683a)
![Screenshot 2024-07-09 at 11 19 39](https://github.com/marco-land/sanity-plugin-vimeo-field/assets/72648825/69327e56-baf0-4399-80e1-960a0fac37c8)

I'm using the source URLs that get returned in the files object which would be the same URLs that I would have used if we were copying and pasting the Vimeo file links from the Vimeo site.

![Screenshot 2024-07-09 at 12 42 27](https://github.com/marco-land/sanity-plugin-vimeo-field/assets/72648825/6d152f81-e04b-4864-aff7-7b654fbfc517)

Any info would be super appreciated.

Thanks,
Jack

**Comment by marco-land** [comment]
Hi Jack,

here's an example of what my data looks like from the Sanity database with the plugin

![CleanShot 2024-07-11 at 12 30 13](https://github.com/marco-land/sanity-plugin-vimeo-field/assets/24410335/14a890b2-ffc7-45ba-994d-4983bd8a74be)

And in my frontend I do something like this, for example when I want to use the 1080p file:
```js
const highResFile = vimeo?.files?.find((file) =>
  file?.rendition?.includes("1080p")
);
videoEl.setAttribute("playsinline", "playsinline");
videoEl.src = highResFile?.link;
```

Does that help?

**Comment by miller-design** [comment]
Hi there,

Apologies for the late reply.

Unfortunately, it doesn't seem to be an issue with how I'm fetching the data but more of an issue on Vimeo's side, I reached out to their support and they responded with the following: "This error is commonly caused by restricted networks or computers (e.g in an office or school), and in some cases, browser extensions or content filter applications. These systems are known to block some of our playback URLs, which can lead to errors in our player."

I'm not 100% sold on the issue related to restricted networks as my office or home and the clients don't have any specific restrictions. I'm waiting to hear back from support but I was hoping someone else may have had a similar issue.

just for context these are the console errors i get on the front end when a video won't load.

(safari error)
![image](https://github.com/user-attachments/assets/95073a2f-eced-42bc-9a96-383c0628ddb1)
(brave error)
![image](https://github.com/user-attachments/assets/6d2c16d9-c019-4e05-a090-e3d07e73f23c)

Cheers,
Jack

**Comment by marco-land** [comment]
No worries! I hope you can find a solution for that edge case -- haven't encountered that one yet.
I will close the issue for now.
