### ISSUE TITLE
No "files" property in response

### ISSUE THREAD

**Issue by Nowopenstudio** [marco-land/sanity-plugin-vimeo-field#8]
Having problems getting the "Files" prop to show up, even manually in options with the latest Sanity Release

-Token has private + video files option selected

Thank you for any help.

**Comment by marco-land** [comment]
Can you let me know how you use the Sanity studio? Is it a Next JS site with an embedded studio?
We noticed there have been problems with an embedded studio setup (https://github.com/marco-land/sanity-plugin-vimeo-field/issues/7)

**Comment by Nowopenstudio** [comment]
Marco,
No, I'm not using an embedded one, standalone sanity on local.

Best,
Ro

**Comment by Nowopenstudio** [comment]
![image](https://github.com/user-attachments/assets/b73992db-91ef-4e34-8a43-5c22b4601384)
![image](https://github.com/user-attachments/assets/1c642544-5f84-4269-96a7-53a61cfe5388)

**Comment by marco-land** [comment]
Ah, I see. It looks like the plugin is working.  

Are you using a Vimeo Pro account? Currently, Vimeo only allows access to raw video files with the Standard plan or higher. [See their pricing](https://vimeo.com/upgrade-plan).  

In case you are on the standard plan (or higher):
The preview will always show `id`, `thumbnail`, and `title` only. However, if you inspect the Sanity document, [see red (1) in my screenshot], can you check the JSON data to confirm if the files are coming through? [See red (2)].  

![CleanShot 2024-12-17 at 10 45 12@2x](https://github.com/user-attachments/assets/2e851422-dcbe-4649-b4af-95891010974e)

**Comment by Nowopenstudio** [comment]
Thank you marco, I have the plus account, not pro! Appreciate it!

**Comment by marco-land** [comment]
No worries -- I think they changed that recently too. I think it used to be possible to access the files with Pro as well...
