### ISSUE TITLE
Bulk refresh option

### ISSUE THREAD

**Issue by maxweisel** [marco-land/sanity-plugin-vimeo-field#9]
We've been using this plugin quite a bit and it's working wonderfully. However, we recently updated thumbnails for all of our videos and going to every page to manually reset them is a huge pain. Any chance of getting a bulk refresh option?

Happy to write the patch myself if you can point me in the right direction.

Max

**Comment by marco-land** [comment]
Hi Max,

Thank you for the feedback! I’m glad to hear the plugin is working well for you.

Regarding your request for a bulk refresh option, unfortunately, this isn’t something the plugin or Sanity can handle natively to my knowledge. The way the plugin is built, it performs a manual fetch and saves the Vimeo API response data based on that specific moment. There’s no built-in mechanism to automatically re-trigger these fetches for all videos.

A possible workaround would be to create a custom Sanity script (e.g. with the [JS client](https://www.sanity.io/docs/js-client)) that performs bulk data updates. This would involve processing each document, fetching the Vimeo data through their API (you can refer to [this file](https://github.com/marco-land/sanity-plugin-vimeo-field/blob/main/src/components/DataFetcher.tsx) to see how the plugin fetches data), and then updating the corresponding Sanity documents.

That said, whether this is worthwhile really depends on how many videos you’re working with and how much manual effort you’re aiming to save…

In general, I’m planning a rewrite of this plugin where I’ll take bulk updates into consideration to address this issue in the future.

Let me know if you’d like any further pointers in the meantime!
